export const SCENE_WORDS = {
  'zh-tw': [
    'Seedance 2.0',
    'Kling 3',
    'Grok Imagine',
    'Runway Gen-3',
    'Sora',
    '圖生影片',
    '多模態參考',
    '電影運鏡',
    '產品廣告',
    'AI 短片',
    '字幕對話',
    '縮時攝影',
  ],
  en: [
    'Seedance 2.0',
    'Kling 3',
    'Grok Imagine',
    'Runway Gen-3',
    'Sora',
    'Image-to-Video',
    'Multimodal Ref',
    'Cinematic Camera',
    'Product Ad',
    'AI Short Film',
    'Dialogue Subtitles',
    'Timelapse',
  ],
};

export const STYLE_WORDS = {
  'zh-tw': [
    '主體動作',
    '鏡頭語言',
    '場景氛圍',
    '音效設計',
    '負向提示',
    '參考圖片',
    '參考影片',
    '畫幅時長',
    '社群精選',
    '一鍵填空',
    '雙語模板',
    '本機儲存',
  ],
  en: [
    'Subject Motion',
    'Camera Language',
    'Scene Mood',
    'Sound Design',
    'Negative Prompt',
    'Image Reference',
    'Video Reference',
    'Aspect & Duration',
    'Community Picks',
    'One-Click Fill',
    'Bilingual Templates',
    'Local Storage',
  ],
};